/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'productInterest' : ProductCategory,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'origin' : string,
  'unit' : string,
  'description' : string,
  'category' : ProductCategory,
}
export type ProductCategory = { 'riceAndGrains' : null } |
  { 'oilseeds' : null } |
  { 'pulsesAndLegumes' : null } |
  { 'fruitsAndVegetables' : null } |
  { 'spices' : null };
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, ProductCategory, string, string, string],
    bigint
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'init' : ActorMethod<[], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, ProductCategory, string],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, ProductCategory, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];