/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'riceAndGrains' : IDL.Null,
  'oilseeds' : IDL.Null,
  'pulsesAndLegumes' : IDL.Null,
  'fruitsAndVegetables' : IDL.Null,
  'spices' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : ProductCategory,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'origin' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'category' : ProductCategory,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, ProductCategory, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'init' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ProductCategory, IDL.Text],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, ProductCategory, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'riceAndGrains' : IDL.Null,
    'oilseeds' : IDL.Null,
    'pulsesAndLegumes' : IDL.Null,
    'fruitsAndVegetables' : IDL.Null,
    'spices' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : ProductCategory,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'origin' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'category' : ProductCategory,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, ProductCategory, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'init' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ProductCategory, IDL.Text],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, ProductCategory, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };